api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--weatherappdb
        value: Server=sql,54782;User ID=sa;Password={{ securedParameter "sql_password" }};TrustServerCertificate=true;Database=WeatherAppDb
      - name: connectionstrings--asb
        value: '{{ .Env.ASB_SERVICEBUSENDPOINT }}'
  template:
    containers:
      - image: {{ .Image }}
        name: eventlistener
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ServiceBus:Inbound__Entities__ModelUpdatedIntegrationEvent
            value: weatherapp-model-updated
          - name: ServiceBus:Inbound__Entities__ModelingDataAcceptedIntegrationEvent
            value: weatherapp-modeling-data-accepted
          - name: ServiceBus:Inbound__Entities__ModelingDataRejectedIntegrationEvent
            value: weatherapp-modeling-data-rejected
          - name: ServiceBus:Inbound__InitialBackoffInMs
            value: "2000"
          - name: ServiceBus:Inbound__MaxConcurrentCalls
            value: "1"
          - name: ServiceBus:Outbound__Entities__UserNotificationEvent
            value: weatherapp-user-notification
          - name: services__contributorpaymentsservice__http__0
            value: http://contributorpaymentsservice.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__contributorpaymentsservice__https__0
            value: https://contributorpaymentsservice.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__queryabletracecollector__http__0
            value: http://queryabletracecollector.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__queryabletracecollector__https__0
            value: https://queryabletracecollector.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__weathermodelingservice__http__0
            value: http://weathermodelingservice.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__weathermodelingservice__https__0
            value: https://weathermodelingservice.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: ConnectionStrings__WeatherAppDb
            secretRef: connectionstrings--weatherappdb
          - name: ConnectionStrings__asb
            secretRef: connectionstrings--asb
    scale:
      minReplicas: 1
tags:
  azd-service-name: eventlistener
  aspire-resource-name: eventlistener
