@baseUrl = https://localhost:7220
@today = {{new Date}}

### Health Check
GET http://localhost:5000/

### Get Weather Forecast
GET http://localhost:5000/v1/weather-forecast/Glastonbury/{{today}}
Content-Type: application/json

### Submit Collected Weather Data
POST http://localhost:5000/v1/collected-weather-data/BA160TE
Content-Type: application/json

{
  "Id": "{{new UUID}}",
  "time": "{{new Date}}",
  "WindSpeed": {
    "Value": 12.5,
    "Unit": "m/s"
  },
  "WindDirection": {
    "Value": "87"
  },
  "Temperature": {
    "Value": 22.3,
    "Unit": "°C"
  },
  "Humidity": {
    "Value": 65,
    "Unit": "%"
  }
}